$engine: 3
$onesync: on

name: ESX Legacy
author: ESX Framework
description: The semi-official recipe of the most popular FiveM RP framework, containing Jobs, Housing, Vehicles & more!

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources/[system]
    dest: ./resources/[cfx-default]/[system]

  # Download server.cfg
  - action: connect_database

  - action: download_github
    src: https://github.com/feelfreetofee/test-recipe
    ref: main
    dest: ./tmp

  - action: move_path
    src: ./tmp/server.cfg
    dest: ./server.cfg

  # Download ESX Core
  - action: download_github
    src: https://github.com/esx-framework/esx-core
    ref: main
    dest: ./tmp/core

  - action: move_path
    src: ./tmp/core/[core]
    dest: ./resources/[core]

  - action: query_database
    file: ./tmp/core/[SQL]/legacy.sql

  # Download ESX Addons
  - action: download_github
    src: https://github.com/esx-framework/ESX-Legacy-Addons
    ref: main
    subpath: ./[esx_addons]
    dest: ./resources/[esx_addons]

  # Download standalone resources
  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  # Download OX resources
  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/CommunityOx/oxmysql/releases/latest/download/oxmysql.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/oxmysql.zip

  - action: download_file
    path: ./tmp/files/ox_lib.zip
    url: https://github.com/CommunityOx/ox_lib/releases/latest/download/ox_lib.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_lib.zip

  - action: download_file
    path: ./tmp/files/ox_inventory.zip
    url: https://github.com/CommunityOx/ox_inventory/releases/latest/download/ox_inventory.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_inventory.zip

  - action: download_file
    path: ./tmp/files/ox_doorlock.zip
    url: https://github.com/CommunityOx/ox_doorlock/releases/latest/download/ox_doorlock.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_doorlock.zip

  - action: download_github
    src: https://github.com/CommunityOx/ox_target
    ref: main
    dest: ./resources/[ox]/ox_target

  - action: download_github
    src: https://github.com/CommunityOx/ox_fuel
    ref: main
    dest: ./resources/[ox]/ox_fuel

  - action: waste_time # prevent github throttling
    seconds: 5

  # Download Illenium Appearance
  - action: download_file
    path: ./tmp/files/illenium-appearance.zip
    url: https://github.com/iLLeniumStudios/illenium-appearance/releases/latest/download/illenium-appearance.zip
  - action: unzip
    dest: ./resources/[standalone]
    src: ./tmp/files/illenium-appearance.zip

  - action: write_file
    file: ./resources/[standalone]/illenium-appearance/fxmanifest.lua
    append: true
    data: 'provides {"esx_skin", "skinchanger"}
    dependency "ox_lib"'

  - action: query_database
    file: ./resources/[standalone]/illenium-appearance/sql/player_outfits.sql

  - action: query_database
    file: ./resources/[standalone]/illenium-appearance/sql/player_outfit_codes.sql

  - action: remove_path
    path: ./resources/[core]/skinchanger

  - action: remove_path
    path: ./resources/[core]/esx_skin

  # Download NPWD
  - action: download_file
    path: ./tmp/files/project-error/screenshot-basic.zip
    url: https://github.com/project-error/screenshot-basic/releases/latest/download/screenshot-basic.zip
  - action: unzip
    dest: ./resources/[standalone]/screenshot-basic
    src: ./tmp/files/project-error/screenshot-basic.zip

  - action: download_file
    path: ./tmp/files/project-error/npwd.zip
    url: https://github.com/project-error/npwd/releases/latest/download/npwd.zip
  - action: unzip
    dest: ./resources/[standalone]
    src: ./tmp/files/project-error/npwd.zip

  - action: query_database
    file: ./resources/[standalone]/npwd/import.sql

  ## Cleanup
  - action: remove_path
    path: ./tmp
